import LeadForm from '../components/LeadForm';

const included=['Custom professional design','Domain registration & setup','First-year Vercel hosting','Mobile optimization','Contact & lead forms','Local SEO foundations','SSL, security & deployment','Launch support'];
const packages=[
 {name:'Turnkey Website',price:'$2,500',monthly:'$625/mo',desc:'A complete business website from concept to launch.',items:['Custom website design & development','Domain setup + first-year hosting','Mobile optimization','Lead & contact forms','Local SEO foundations','SSL, security & deployment']},
 {name:'Website + Professional Media',price:'$3,500',monthly:'$875/mo',featured:true,desc:'Everything in Turnkey, plus we come to your business and capture it properly.',items:['Everything in Turnkey Website','On-location photography','Professional video capture','Custom visual content','Authentic team, space & work imagery','Launch-ready media library']}
];
const process=[['1','Discovery','We learn about your business, goals and style.'],['2','Design & Build','We design, develop and bring your site to life.'],['3','Media (Optional)','We capture photos and video at your location.'],['4','Launch','We test, deploy and get you live.']];
export default function Home(){return <main>
<header className="site-header"><a className="brand" href="#top"><span className="brand-emblem">⚓</span><span><strong>NEW BERN</strong><small>WEBSITES</small><i>We Handle Everything.</i></span></a><nav><a href="#top">Home</a><a href="#services">Services</a><a href="#pricing">Packages</a><a href="#process">Process</a><a href="#contact">Contact</a><a className="nav-cta" href="#contact">Start Your Website →</a></nav></header>
<section className="hero" id="top"><div className="hero-shade"></div><div className="hero-inner"><p className="eyebrow light-eye">BUILT IN NEW BERN. BUILT FOR NEW BERN.</p><h1>Your Business Deserves<br/>a <em>Better Website.</em></h1><p className="lead">Beautiful, high-performance websites for local businesses — with the domain, hosting, design, development and launch handled for you.</p><div className="actions"><a className="button gold" href="#contact">Start Your Website →</a><a className="button outline-light" href="#pricing">See Packages</a></div><p className="micro">Starting at <strong>$625/month</strong> with our simple payment plan.</p></div><div className="local-note"><em>Local. Professional. Trusted.</em><span>New Bern, NC</span></div></section>
<section className="feature-strip" id="services">{[['✦','Custom Design','Built for Your Brand'],['▣','Mobile Ready','Looks Great Everywhere'],['⌕','SEO Setup','Get Found Locally'],['◇','Fast & Secure','SSL, Hosting, Updates']].map(x=><div key={x[1]}><b>{x[0]}</b><span><strong>{x[1]}</strong><small>{x[2]}</small></span></div>)}</section>
<section className="packages" id="pricing"><div className="section-title"><p className="eyebrow">WE HANDLE EVERYTHING.</p><h2>Simple Packages. <em>Big Results.</em></h2><p>Choose the package that fits your business. We handle everything so you can focus on what you do best.</p></div><div className="package-layout"><aside className="included"><h3>Everything You Need.<br/>All Included.</h3>{included.map(i=><p key={i}><b>✓</b>{i}</p>)}</aside><div className="package-cards">{packages.map(p=><article className={p.featured?'package-card featured':'package-card'} key={p.name}>{p.featured&&<div className="popular">MOST POPULAR</div>}<div className="package-icon">{p.featured?'◉':'▣'}</div><h3>{p.name}</h3><p className="desc">{p.desc}</p><div className="price">{p.price}</div><small>or 4 payments of</small><strong className="monthly">{p.monthly}</strong><ul>{p.items.map(i=><li key={i}>✓ {i}</li>)}</ul><a className="button package-button" href="#contact">Get Started</a></article>)}</div></div>
<div className="radio-card"><div className="radio-mark">97.1</div><div><p className="eyebrow light-eye">WEBSITE + LOCAL EXPOSURE</p><h3>Don’t just launch your website. Tell New Bern about it.</h3><p>Add a three-month promotional campaign on Captain 97.1 to either website package.</p></div><div className="radio-price"><span>3 MONTHS</span><strong>+$500</strong></div></div>
<div className="payment-bar"><div><b>▦</b><span><strong>Simple Payment Plan</strong><small>25% down, then 3 equal monthly payments. No complicated financing.</small></span></div><div><span>$2,500 →</span><strong>$625/month</strong></div><div><span>$3,500 →</span><strong>$875/month</strong></div></div></section>
<section className="process-contact" id="process"><div className="process-side"><p className="eyebrow">OUR PROCESS</p><h2>Easy. Professional.<br/><em>Completely handled.</em></h2><div className="process-grid">{process.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div><div className="lower-grid"><article className="custom-card"><p className="eyebrow">LARGER PROJECTS?</p><h3>Custom solutions are welcome.</h3><p>E-commerce, booking systems, customer portals, catalogs and specialized integrations are available by custom quote.</p></article><article className="care-card"><p className="eyebrow">AFTER YEAR ONE</p><h3>New Bern Websites Care</h3><div><strong>$49</strong><span>/month</span></div><p>Hosting · Domain renewal coordination · SSL · Security · Monitoring · Reasonable content updates</p></article></div></div><div className="form-card" id="contact"><p className="eyebrow light-eye">LET’S BUILD IT.</p><h2>Start Your Website</h2><p>Tell us a little about your business and we’ll be in touch.</p><LeadForm/><div className="office"><span>NEW BERN OFFICE</span><strong>1423 South Glenburnie Road, Suite C</strong><small>New Bern, NC 28562</small></div></div></section>
<section className="local-banner"><div><p className="eyebrow light-eye">PROUDLY LOCAL</p><h2>Let’s build something great.</h2><p>Your website. Our expertise. A stronger New Bern.</p></div><a href="#contact" className="button gold">Start Your Website →</a></section>
<footer><div className="footer-brand"><div className="brand"><span className="brand-emblem">⚓</span><span><strong>NEW BERN</strong><small>WEBSITES</small><i>We Handle Everything.</i></span></div></div><div><strong>Contact</strong><p>1423 South Glenburnie Road, Suite C<br/>New Bern, NC 28562</p><p>newbernwebsites.com</p></div><div><strong>Quick Links</strong><p><a href="#services">Services</a> · <a href="#pricing">Packages</a><br/><a href="#process">Process</a> · <a href="#contact">Contact</a></p></div><div><strong>Local business. Local support.</strong><p>Serving New Bern and Eastern North Carolina.</p></div></footer>
</main>}
