const packages = [
  { name:'Turnkey Website', price:'$2,500', monthly:'4 payments of $625', featured:false, description:'A complete, professionally designed business website from concept to launch.', items:['Custom website design & development','Domain setup + first-year hosting','Mobile optimization','Lead & contact forms','Local SEO foundations','SSL, security & deployment'] },
  { name:'Website + Professional Media', price:'$3,500', monthly:'4 payments of $875', featured:true, description:'Everything in our turnkey package, plus we come to your business and capture the real story.', items:['Everything in Turnkey Website','On-location photography','Professional video capture','Custom visual content','Authentic team, space & work imagery','Launch-ready media library'] }
];
const services=[['01','Design & Development','Custom-built around your business — never a generic template.'],['02','Domain & Hosting','Domain connection, first-year hosting, SSL and deployment handled.'],['03','Photography & Video','We can come to your business and capture the people, space and work that make it yours.'],['04','Local SEO','Strong technical and on-page foundations for New Bern-area search.']];
export default function Home(){return <main>
<header className="site-header"><a className="brand" href="#top"><span className="seal">NB</span><span><strong>NEW BERN</strong><small>WEBSITES</small></span></a><nav><a href="#services">Services</a><a href="#pricing">Pricing</a><a href="#process">Process</a><a className="nav-cta" href="#contact">Start Your Website</a></nav></header>
<section className="hero" id="top"><div className="hero-inner"><p className="eyebrow">BUILT IN NEW BERN · BUILT FOR NEW BERN</p><h1>Your business deserves a <em>better website.</em></h1><p className="lead">Beautiful, high-end websites for local businesses — with the domain, hosting, design, development and launch handled for you.</p><div className="actions"><a className="button primary" href="#contact">Start Your Website</a><a className="button secondary" href="#pricing">See Packages</a></div><p className="micro">Starting at <strong>$625/month</strong> with our simple payment plan.</p></div><div className="waterline"/></section>
<section className="intro" id="services"><p className="eyebrow">WE HANDLE EVERYTHING.</p><h2>One local team.<br/><em>One polished presence.</em></h2><p className="intro-copy">You run your business. We handle the website — strategy, design, development, domain, hosting, launch and the details that usually make website projects a headache.</p><div className="service-grid">{services.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="pricing" id="pricing"><div className="heading"><p className="eyebrow">SIMPLE PRICING</p><h2>Choose how hands-off<br/>you want to be.</h2><p>No confusing menu of technical services. Pick the level that fits your business and we take it from there.</p></div><div className="pricing-grid">{packages.map(p=><article className={p.featured?'price-card featured':'price-card'} key={p.name}>{p.featured&&<div className="popular">MOST POPULAR</div>}<h3>{p.name}</h3><div className="price">{p.price}</div><strong className="monthly">{p.monthly}</strong><p>{p.description}</p><ul>{p.items.map(i=><li key={i}>✓ {i}</li>)}</ul><a href="#contact" className="button primary full">Choose This Package</a></article>)}</div><div className="radio"><div><p className="eyebrow">OPTIONAL LOCAL LAUNCH BOOST</p><h3>Get your new website heard.</h3><p>Add a three-month promotional campaign on Captain 97.1 to either website package. Your website stays the star — radio helps New Bern discover it.</p></div><div><span>3 MONTHS</span><strong>+$500</strong></div></div></section>
<section className="payment"><div><p className="eyebrow">SIMPLE PAYMENT PLAN</p><h2>Start with 25%.<br/><em>We’ll take it from there.</em></h2></div><div><p>No complicated financing application. Put 25% down when your project begins and spread the remaining balance across the following three months.</p><div className="payrow"><span>$2,500 Turnkey Website</span><strong>$625 × 4</strong></div><div className="payrow"><span>$3,500 Website + Media</span><strong>$875 × 4</strong></div></div></section>
<section className="process" id="process"><p className="eyebrow">OUR PROCESS</p><h2>From “we need a website”<br/>to <em>live.</em></h2><div className="process-grid">{[['01','Tell us about your business'],['02','We build the foundation'],['03','We create'],['04','We launch']].map(([n,t])=><article key={n}><span>{n}</span><h3>{t}</h3></article>)}</div></section>
<section className="care"><p className="eyebrow">AFTER YEAR ONE</p><h2>Your website stays cared for.</h2><p>First-year hosting is included. After that, New Bern Websites Care keeps hosting, SSL, security, monitoring, domain renewal coordination and reasonable content updates under one roof.</p><div className="care-price"><strong>$49</strong><span>/ month</span></div></section>
<section className="custom"><p className="eyebrow">NEED SOMETHING BIGGER?</p><h2>Custom projects are welcome.</h2><p>E-commerce, booking systems, customer portals, advanced integrations and specialized builds are available by custom quote.</p></section>
<section className="contact" id="contact"><div><p className="eyebrow">LET'S BUILD IT.</p><h2>Ready for a website that represents your business properly?</h2><p className="contact-copy">Tell us about your business. We’ll take it from there.</p><div className="contact-address"><span>NEW BERN OFFICE</span><strong>1423 South Glenburnie Road, Suite C</strong><p>New Bern, NC 28562</p></div></div><form action="mailto:hello@newbernwebsites.com" method="post" encType="text/plain"><input name="name" placeholder="Your name" required/><input name="business" placeholder="Business name" required/><input type="email" name="email" placeholder="Email address" required/><textarea name="project" rows={5} placeholder="Tell us about your business and what you need."/><button className="button primary full">Start Your Website</button></form></section>
<footer><div className="brand"><span className="seal">NB</span><span><strong>NEW BERN</strong><small>WEBSITES</small></span></div><p>WE HANDLE EVERYTHING.</p><p>1423 South Glenburnie Road, Suite C · New Bern, NC 28562<br/>newbernwebsites.com</p></footer>
</main>}