export type OutreachLead = {
  key: string;
  business: string;
  email: string;
  sourceUrl: string;
  observation: string;
  recommendedPackage: 'Turnkey Website' | 'Media Website';
  subject: string;
  body: string;
};

// Every address below was copied from the business's own public website.
// The cron sends at most three new first touches per weekday. Replies are handled
// independently, so increasing this queue does not increase the daily send cap.
export const OUTREACH_QUEUE: OutreachLead[] = [
  {
    key: 'dlo-construction-2026-08',
    business: 'DLO Construction',
    email: 'dlocontractorsllc@gmail.com',
    sourceUrl: 'https://www.dloconstructionllc.com/',
    observation: 'Repeated starting prices and an outdated third-party footer weaken the quote path.',
    recommendedPackage: 'Turnkey Website',
    subject: 'A quick website observation',
    body: [
      'Hi DLO Construction team,',
      '',
      'I was reviewing your online booking flow and noticed that several starting prices repeat and the request page still shows a 2035 footer with a third-party label. Those small details can make an otherwise strong contractor look less current right when a homeowner is deciding whether to request a quote.',
      '',
      'I run New Bern Websites locally. We rebuild service-business sites around a cleaner quote path, mobile clarity, and local search visibility.',
      '',
      "If improving that flow is already on your list, I can send a short outline of what I'd change.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'atlantic-coast-landscape-2026-08',
    business: 'Atlantic Coast Landscape',
    email: 'info@atlanticcoastlandscape.net',
    sourceUrl: 'https://atlanticcoastlandscape.net/contact-us/',
    observation: 'The mobile quote path asks for a long form and image verification before contact.',
    recommendedPackage: 'Media Website',
    subject: 'Quick thought on your contact page',
    body: [
      'Hi Atlantic Coast Landscape team,',
      '',
      'I was looking through your site and noticed that the contact path asks prospects to complete a fairly long form plus image verification before they can reach you. On a phone, that extra friction can cost otherwise solid quote requests.',
      '',
      'I run New Bern Websites locally. We build service-business sites around a faster mobile quote path, clear proof of work, and local search visibility.',
      '',
      "If simplifying that path is useful, I can send a short outline of what I'd change.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'new-bern-referrals-2026-08',
    business: 'New Bern Business Referral Network',
    email: 'newbernreferrals@gmail.com',
    sourceUrl: 'https://newbernreferrals.com/',
    observation: 'The live homepage contains placeholder testimonial names and copy.',
    recommendedPackage: 'Turnkey Website',
    subject: 'Small issue on the NBBRN homepage',
    body: [
      'Hi NBBRN team,',
      '',
      'I noticed the live homepage is still showing placeholder testimonial copy and names such as “Founder of xyz.com.” Because the site represents a group of trusted local businesses, that section may be undercutting the credibility the rest of the organization has built.',
      '',
      'I run New Bern Websites locally. We help organizations clean up those trust gaps and make the path from visitor to inquiry much clearer.',
      '',
      "If it would help, I can send a short outline of the changes I'd prioritize.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'new-bern-cleaning-2026-08',
    business: 'New Bern Cleaning',
    email: 'newberncleaningservice@gmail.com',
    sourceUrl: 'https://www.cleaningnewbern.com/',
    observation: 'The site has a very short service story and limited proof before the quote form.',
    recommendedPackage: 'Media Website',
    subject: 'A quick idea for your quote page',
    body: [
      'Hi New Bern Cleaning team,',
      '',
      'I found your site while reviewing local cleaning companies. The contact path is easy to find, but a new visitor sees very little proof of the different spaces you clean or what makes the service dependable before being asked to submit their details.',
      '',
      'I run New Bern Websites locally. We build service-business sites that pair a fast quote path with clear packages, local proof, and strong before-and-after visuals.',
      '',
      "If that is worth improving, I can send a short outline of what I'd change.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'king-of-the-greens-2026-08',
    business: 'King of the Greens',
    email: 'kingofthegreenllc@gmail.com',
    sourceUrl: 'https://www.kingofthegreenllc.com/',
    observation: 'A stronger project gallery and mobile estimate path could better showcase high-value landscape work.',
    recommendedPackage: 'Media Website',
    subject: 'Quick website thought for King of the Greens',
    body: [
      'Hi King of the Greens team,',
      '',
      'I was looking through your site and noticed the range of landscaping, drainage, and sod work you handle. A more visual mobile-first project gallery tied directly to a short estimate request could make that range easier for homeowners to understand and act on.',
      '',
      'I run New Bern Websites locally. We build service-business sites around strong project proof, a clean quote path, and local search visibility.',
      '',
      "If useful, I can send a short outline of the changes I'd prioritize.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'top-choice-lawn-2026-08',
    business: 'Top Choice Lawn Maintenance',
    email: 'topchoicelawnservice@gmail.com',
    sourceUrl: 'https://topchoicelawnmaintenance.com/landscaping-services/landscaping-company/',
    observation: 'The service pages could route visitors into a shorter, more consistent estimate funnel.',
    recommendedPackage: 'Media Website',
    subject: 'One idea for your estimate flow',
    body: [
      'Hi Top Choice Lawn Maintenance team,',
      '',
      'I came across your landscaping pages while reviewing local service businesses. You cover a wide range of work, but the path from an individual service page to a clear mobile estimate request could be much tighter and more consistent.',
      '',
      'I run New Bern Websites locally. We build service-business sites that turn project photos and service pages into a faster quote path.',
      '',
      "If you are open to it, I can send a short outline of what I'd change.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'roof-pro-nc-2026-08',
    business: 'Roof Pro NC',
    email: 'roofpronc1@gmail.com',
    sourceUrl: 'https://www.carolinaroofpro.com/',
    observation: 'Local project proof and a clearer New Bern-specific inspection path could strengthen conversion.',
    recommendedPackage: 'Media Website',
    subject: 'Quick website idea for Roof Pro NC',
    body: [
      'Hi Roof Pro NC team,',
      '',
      'I found your site while reviewing New Bern roofing companies. The contact information is clear, but a stronger New Bern-specific inspection path supported by recent local project photos could give homeowners more confidence before they call.',
      '',
      'I run New Bern Websites locally. We build contractor sites around project proof, fast inspection requests, and local search visibility.',
      '',
      "If useful, I can send a short outline of what I'd change.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'river-dog-plumbing-2026-08',
    business: 'River Dog Plumbing & Heating',
    email: 'riverdogplumbing@gmail.com',
    sourceUrl: 'https://www.riverdogplumbing.com/',
    observation: 'The mascot and local story are distinctive; service-area landing pages could turn that brand into more search traffic.',
    recommendedPackage: 'Turnkey Website',
    subject: 'A local-search idea for River Dog',
    body: [
      'Hi River Dog Plumbing team,',
      '',
      'Your name, mascot, and local story are memorable. I noticed there may be an opportunity to build that strong brand into clearer service-area pages for plumbing, drains, gas piping, and heating so more nearby searches lead into the contact flow.',
      '',
      'I run New Bern Websites locally. We build service-business sites around focused local pages, mobile clarity, and a fast inquiry path.',
      '',
      "If that sounds useful, I can send a short outline of what I'd prioritize.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'cayton-plumbing-2026-08',
    business: 'Cayton Plumbing',
    email: 'contact@jlcayton.com',
    sourceUrl: 'https://www.jlcayton.com/',
    observation: 'Commercial, utility, and residential capabilities could be separated into clearer customer journeys.',
    recommendedPackage: 'Turnkey Website',
    subject: 'Quick thought on the Cayton Plumbing site',
    body: [
      'Hi Cayton Plumbing team,',
      '',
      'I was looking through your site and noticed you serve several different needs, from residential plumbing to commercial and utility work. Those audiences could be separated into clearer paths so each visitor immediately sees the right proof and next step.',
      '',
      'I run New Bern Websites locally. We build service-business sites around clear customer journeys, mobile inquiries, and local search visibility.',
      '',
      "If useful, I can send a short outline of what I'd change.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'letchworth-plumbing-2026-08',
    business: 'Letchworth Plumbing',
    email: 'lasplumbingllc@gmail.com',
    sourceUrl: 'https://letchworthplumbing.com/',
    observation: 'The breadth of residential, commercial, and service work could be supported by stronger local proof and project detail.',
    recommendedPackage: 'Turnkey Website',
    subject: 'A website idea for Letchworth Plumbing',
    body: [
      'Hi Letchworth Plumbing team,',
      '',
      'I came across your site while looking at New Bern plumbing companies. Your residential, commercial, and service experience is a strong story; adding more local project proof and clearer service-specific inquiry paths could make that experience work harder online.',
      '',
      'I run New Bern Websites locally. We build service-business sites around trust, focused service pages, and a fast quote path.',
      '',
      "If useful, I can send a short outline of what I'd prioritize.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'hermetic-roofing-2026-08',
    business: 'Hermetic Roofing',
    email: 'info@hermeticroofing.com',
    sourceUrl: 'https://hermeticroofing.com/',
    observation: 'The current footer names another roofing brand, which may confuse prospects at a trust-sensitive point.',
    recommendedPackage: 'Turnkey Website',
    subject: 'Small trust issue on the Hermetic Roofing site',
    body: [
      'Hi Hermetic Roofing team,',
      '',
      'I noticed the footer on the current site says “Copyright 2026 Rooftops Unlimited.” Because homeowners are making a trust-sensitive decision, that different company name could create unnecessary doubt right before they request a quote.',
      '',
      'I run New Bern Websites locally. We rebuild contractor sites around consistent branding, clear proof, and a faster quote path.',
      '',
      "If helpful, I can send a short outline of the other changes I'd prioritize.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 're-bengel-2026-08',
    business: 'R.E. Bengel Sheet Metal',
    email: 'lisa@rebengel.com',
    sourceUrl: 'https://www.rebengel.com/contact',
    observation: 'A century-old local reputation could be presented with a more modern project and estimate experience.',
    recommendedPackage: 'Media Website',
    subject: 'A website thought for R.E. Bengel',
    body: [
      'Hi Lisa,',
      '',
      'R.E. Bengel has a local history most contractors cannot match. I was looking through the site and thought that a more modern project gallery and estimate flow could do a stronger job of translating that century-plus reputation for homeowners on mobile.',
      '',
      'I run New Bern Websites locally. We build contractor sites around authentic project proof, local trust, and a fast estimate path.',
      '',
      "If useful, I can send a short outline of what I'd change.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'cleaning-by-kate-2026-08',
    business: 'Cleaning by Kate',
    email: 'kate@cleaningbykate.com',
    sourceUrl: 'https://www.cleaningbykate.com/',
    observation: 'The long homepage repeats several calls to action before the estimate form, making the mobile journey feel heavy.',
    recommendedPackage: 'Media Website',
    subject: 'One mobile-site idea for Cleaning by Kate',
    body: [
      'Hi Kate,',
      '',
      'Your reviews, guarantees, and community work give you excellent trust material. On mobile, though, the homepage becomes a long journey with several repeated calls to action before the estimate form, so some visitors may never reach the strongest proof.',
      '',
      'I run New Bern Websites locally. We build service-business sites that keep the trust while making the path to an estimate much faster.',
      '',
      "If useful, I can send a short outline of how I'd simplify it.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
];
