export type OutreachLead = {
  key: string;
  business: string;
  email: string;
  sourceUrl: string;
  observation: string;
  recommendedPackage: 'Turnkey Website' | 'Media Website';
  subject: string;
  body: string;
};

// Every address below was copied from the business's own public website.
// The cron ramps from 15 to 50 new first touches per weekday, spread across
// five-message hourly batches. Replies and follow-ups are handled independently.
export const OUTREACH_QUEUE: OutreachLead[] = [
  {
    key: 'firefly-cafe-2026-08',
    business: 'Firefly Café',
    email: 'info@fireflycafenewbern.com',
    sourceUrl: 'https://www.fireflycafenewbern.com/',
    observation: 'Some current event pages surface under a temporary Squarespace address, while the ticket store can show no results despite an event ticket being available.',
    recommendedPackage: 'Media Website',
    subject: 'A small website issue I found for Firefly',
    body: [
      'Hi Shaun,',
      '',
      'I was looking through Firefly’s events and ticketing pages and noticed that some current event pages are surfacing under a temporary Squarespace address instead of Firefly’s domain. The ticket store can also show “No results found” even while an event ticket is available elsewhere on the site.',
      '',
      'For a business built around live music, wine dinners, private events, and repeat visits, that disconnect can create friction and keep those pages from doing as much for local search as they should.',
      '',
      'I run New Bern Websites locally. We build and manage sites around strong visual storytelling, clean event and booking paths, and a polished mobile experience.',
      '',
      "If tightening that flow is already on your list, I can send a short, no-pressure outline of what I’d prioritize.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'the-harvey-2026-08',
    business: 'The Harvey',
    email: 'info@heronhospitality.com',
    sourceUrl: 'https://harveync.com/',
    observation: 'The historic story, room details, and direct-booking message could be joined into a tighter mobile path supported by richer local content.',
    recommendedPackage: 'Media Website',
    subject: 'A direct-booking idea for The Harvey',
    body: [
      'Hi Charles,',
      '',
      'The Harvey has an unusually strong story—the restoration, ten-room boutique format, and smart keyless guest experience are all genuinely distinctive. On the current site, though, the history, room details, and direct-booking message are spread across several separate pages and steps.',
      '',
      'A tighter mobile booking path, paired with richer photo and video storytelling and useful New Bern itinerary content, could give prospective guests more reasons to book directly instead of returning to an online travel agency.',
      '',
      'I run New Bern Websites locally. We build and manage conversion-focused sites for Eastern North Carolina businesses, including original photography and short-form video when the brand calls for it.',
      '',
      "If that direction is worth exploring, I can send a concise outline of what I’d prioritize.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'dlo-construction-2026-08',
    business: 'DLO Construction',
    email: 'dlocontractorsllc@gmail.com',
    sourceUrl: 'https://www.dloconstructionllc.com/',
    observation: 'Repeated starting prices and an outdated third-party footer weaken the quote path.',
    recommendedPackage: 'Turnkey Website',
    subject: 'A quick website observation',
    body: [
      'Hi DLO Construction team,',
      '',
      'I was reviewing your online booking flow and noticed that several starting prices repeat and the request page still shows a 2035 footer with a third-party label. Those small details can make an otherwise strong contractor look less current right when a homeowner is deciding whether to request a quote.',
      '',
      'I run New Bern Websites locally. We rebuild service-business sites around a cleaner quote path, mobile clarity, and local search visibility.',
      '',
      "If improving that flow is already on your list, I can send a short outline of what I'd change.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'atlantic-coast-landscape-2026-08',
    business: 'Atlantic Coast Landscape',
    email: 'info@atlanticcoastlandscape.net',
    sourceUrl: 'https://atlanticcoastlandscape.net/contact-us/',
    observation: 'The mobile quote path asks for a long form and image verification before contact.',
    recommendedPackage: 'Media Website',
    subject: 'Quick thought on your contact page',
    body: [
      'Hi Atlantic Coast Landscape team,',
      '',
      'I was looking through your site and noticed that the contact path asks prospects to complete a fairly long form plus image verification before they can reach you. On a phone, that extra friction can cost otherwise solid quote requests.',
      '',
      'I run New Bern Websites locally. We build service-business sites around a faster mobile quote path, clear proof of work, and local search visibility.',
      '',
      "If simplifying that path is useful, I can send a short outline of what I'd change.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'new-bern-referrals-2026-08',
    business: 'New Bern Business Referral Network',
    email: 'newbernreferrals@gmail.com',
    sourceUrl: 'https://newbernreferrals.com/',
    observation: 'The live homepage contains placeholder testimonial names and copy.',
    recommendedPackage: 'Turnkey Website',
    subject: 'Small issue on the NBBRN homepage',
    body: [
      'Hi NBBRN team,',
      '',
      'I noticed the live homepage is still showing placeholder testimonial copy and names such as “Founder of xyz.com.” Because the site represents a group of trusted local businesses, that section may be undercutting the credibility the rest of the organization has built.',
      '',
      'I run New Bern Websites locally. We help organizations clean up those trust gaps and make the path from visitor to inquiry much clearer.',
      '',
      "If it would help, I can send a short outline of the changes I'd prioritize.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'new-bern-cleaning-2026-08',
    business: 'New Bern Cleaning',
    email: 'newberncleaningservice@gmail.com',
    sourceUrl: 'https://www.cleaningnewbern.com/',
    observation: 'The site has a very short service story and limited proof before the quote form.',
    recommendedPackage: 'Media Website',
    subject: 'A quick idea for your quote page',
    body: [
      'Hi New Bern Cleaning team,',
      '',
      'I found your site while reviewing local cleaning companies. The contact path is easy to find, but a new visitor sees very little proof of the different spaces you clean or what makes the service dependable before being asked to submit their details.',
      '',
      'I run New Bern Websites locally. We build service-business sites that pair a fast quote path with clear packages, local proof, and strong before-and-after visuals.',
      '',
      "If that is worth improving, I can send a short outline of what I'd change.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'king-of-the-greens-2026-08',
    business: 'King of the Greens',
    email: 'kingofthegreenllc@gmail.com',
    sourceUrl: 'https://www.kingofthegreenllc.com/',
    observation: 'A stronger project gallery and mobile estimate path could better showcase high-value landscape work.',
    recommendedPackage: 'Media Website',
    subject: 'Quick website thought for King of the Greens',
    body: [
      'Hi King of the Greens team,',
      '',
      'I was looking through your site and noticed the range of landscaping, drainage, and sod work you handle. A more visual mobile-first project gallery tied directly to a short estimate request could make that range easier for homeowners to understand and act on.',
      '',
      'I run New Bern Websites locally. We build service-business sites around strong project proof, a clean quote path, and local search visibility.',
      '',
      "If useful, I can send a short outline of the changes I'd prioritize.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'top-choice-lawn-2026-08',
    business: 'Top Choice Lawn Maintenance',
    email: 'topchoicelawnservice@gmail.com',
    sourceUrl: 'https://topchoicelawnmaintenance.com/landscaping-services/landscaping-company/',
    observation: 'The service pages could route visitors into a shorter, more consistent estimate funnel.',
    recommendedPackage: 'Media Website',
    subject: 'One idea for your estimate flow',
    body: [
      'Hi Top Choice Lawn Maintenance team,',
      '',
      'I came across your landscaping pages while reviewing local service businesses. You cover a wide range of work, but the path from an individual service page to a clear mobile estimate request could be much tighter and more consistent.',
      '',
      'I run New Bern Websites locally. We build service-business sites that turn project photos and service pages into a faster quote path.',
      '',
      "If you are open to it, I can send a short outline of what I'd change.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'roof-pro-nc-2026-08',
    business: 'Roof Pro NC',
    email: 'roofpronc1@gmail.com',
    sourceUrl: 'https://www.carolinaroofpro.com/',
    observation: 'Local project proof and a clearer New Bern-specific inspection path could strengthen conversion.',
    recommendedPackage: 'Media Website',
    subject: 'Quick website idea for Roof Pro NC',
    body: [
      'Hi Roof Pro NC team,',
      '',
      'I found your site while reviewing New Bern roofing companies. The contact information is clear, but a stronger New Bern-specific inspection path supported by recent local project photos could give homeowners more confidence before they call.',
      '',
      'I run New Bern Websites locally. We build contractor sites around project proof, fast inspection requests, and local search visibility.',
      '',
      "If useful, I can send a short outline of what I'd change.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'river-dog-plumbing-2026-08',
    business: 'River Dog Plumbing & Heating',
    email: 'riverdogplumbing@gmail.com',
    sourceUrl: 'https://www.riverdogplumbing.com/',
    observation: 'The mascot and local story are distinctive; service-area landing pages could turn that brand into more search traffic.',
    recommendedPackage: 'Turnkey Website',
    subject: 'A local-search idea for River Dog',
    body: [
      'Hi River Dog Plumbing team,',
      '',
      'Your name, mascot, and local story are memorable. I noticed there may be an opportunity to build that strong brand into clearer service-area pages for plumbing, drains, gas piping, and heating so more nearby searches lead into the contact flow.',
      '',
      'I run New Bern Websites locally. We build service-business sites around focused local pages, mobile clarity, and a fast inquiry path.',
      '',
      "If that sounds useful, I can send a short outline of what I'd prioritize.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'cayton-plumbing-2026-08',
    business: 'Cayton Plumbing',
    email: 'contact@jlcayton.com',
    sourceUrl: 'https://www.jlcayton.com/',
    observation: 'Commercial, utility, and residential capabilities could be separated into clearer customer journeys.',
    recommendedPackage: 'Turnkey Website',
    subject: 'Quick thought on the Cayton Plumbing site',
    body: [
      'Hi Cayton Plumbing team,',
      '',
      'I was looking through your site and noticed you serve several different needs, from residential plumbing to commercial and utility work. Those audiences could be separated into clearer paths so each visitor immediately sees the right proof and next step.',
      '',
      'I run New Bern Websites locally. We build service-business sites around clear customer journeys, mobile inquiries, and local search visibility.',
      '',
      "If useful, I can send a short outline of what I'd change.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'letchworth-plumbing-2026-08',
    business: 'Letchworth Plumbing',
    email: 'lasplumbingllc@gmail.com',
    sourceUrl: 'https://letchworthplumbing.com/',
    observation: 'The breadth of residential, commercial, and service work could be supported by stronger local proof and project detail.',
    recommendedPackage: 'Turnkey Website',
    subject: 'A website idea for Letchworth Plumbing',
    body: [
      'Hi Letchworth Plumbing team,',
      '',
      'I came across your site while looking at New Bern plumbing companies. Your residential, commercial, and service experience is a strong story; adding more local project proof and clearer service-specific inquiry paths could make that experience work harder online.',
      '',
      'I run New Bern Websites locally. We build service-business sites around trust, focused service pages, and a fast quote path.',
      '',
      "If useful, I can send a short outline of what I'd prioritize.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'hermetic-roofing-2026-08',
    business: 'Hermetic Roofing',
    email: 'info@hermeticroofing.com',
    sourceUrl: 'https://hermeticroofing.com/',
    observation: 'The current footer names another roofing brand, which may confuse prospects at a trust-sensitive point.',
    recommendedPackage: 'Turnkey Website',
    subject: 'Small trust issue on the Hermetic Roofing site',
    body: [
      'Hi Hermetic Roofing team,',
      '',
      'I noticed the footer on the current site says “Copyright 2026 Rooftops Unlimited.” Because homeowners are making a trust-sensitive decision, that different company name could create unnecessary doubt right before they request a quote.',
      '',
      'I run New Bern Websites locally. We rebuild contractor sites around consistent branding, clear proof, and a faster quote path.',
      '',
      "If helpful, I can send a short outline of the other changes I'd prioritize.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 're-bengel-2026-08',
    business: 'R.E. Bengel Sheet Metal',
    email: 'lisa@rebengel.com',
    sourceUrl: 'https://www.rebengel.com/contact',
    observation: 'A century-old local reputation could be presented with a more modern project and estimate experience.',
    recommendedPackage: 'Media Website',
    subject: 'A website thought for R.E. Bengel',
    body: [
      'Hi Lisa,',
      '',
      'R.E. Bengel has a local history most contractors cannot match. I was looking through the site and thought that a more modern project gallery and estimate flow could do a stronger job of translating that century-plus reputation for homeowners on mobile.',
      '',
      'I run New Bern Websites locally. We build contractor sites around authentic project proof, local trust, and a fast estimate path.',
      '',
      "If useful, I can send a short outline of what I'd change.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'cleaning-by-kate-2026-08',
    business: 'Cleaning by Kate',
    email: 'kate@cleaningbykate.com',
    sourceUrl: 'https://www.cleaningbykate.com/',
    observation: 'The long homepage repeats several calls to action before the estimate form, making the mobile journey feel heavy.',
    recommendedPackage: 'Media Website',
    subject: 'One mobile-site idea for Cleaning by Kate',
    body: [
      'Hi Kate,',
      '',
      'Your reviews, guarantees, and community work give you excellent trust material. On mobile, though, the homepage becomes a long journey with several repeated calls to action before the estimate form, so some visitors may never reach the strongest proof.',
      '',
      'I run New Bern Websites locally. We build service-business sites that keep the trust while making the path to an estimate much faster.',
      '',
      "If useful, I can send a short outline of how I'd simplify it.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'klm-plumbing-2026-08',
    business: 'KLM Plumbing LLC',
    email: 'klmplumbing@gmail.com',
    sourceUrl: 'https://newbernbuilders.com/member/klm-plumbing-llc/',
    observation: 'Branded searches lead to association and review pages instead of an owned service and booking site.',
    recommendedPackage: 'Turnkey Website',
    subject: 'A website idea for KLM Plumbing',
    body: [
      'Hi Marion,',
      '',
      'I found KLM Plumbing through the local builders directory. A branded search currently leads customers into association, job, and review pages rather than an owned site with clear services and a direct request path.',
      '',
      'I run New Bern Websites locally. We build complete service-business sites around mobile calls, quote requests, and local search visibility.',
      '',
      "If useful, I can send a short outline of the pages I'd prioritize.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'elr-construction-2026-08',
    business: 'ELR Construction Services',
    email: 'lenreason@yahoo.com',
    sourceUrl: 'https://newbernbuilders.com/member/ernest-reason-construction/',
    observation: 'Active homes and third-party profiles surface in search, but no owned portfolio or inquiry path appears.',
    recommendedPackage: 'Media Website',
    subject: 'A portfolio idea for ELR Construction',
    body: [
      'Hi ELR Construction team,',
      '',
      'I found active homes and contractor profiles for ELR in search, but I did not find an owned portfolio where a prospective client can see your work and start a direct conversation.',
      '',
      'I run New Bern Websites locally. We build contractor sites around authentic project photos, clear services, and a simple consultation path.',
      '',
      "If useful, I can send a short outline of what I'd build first.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'james-arthur-construction-2026-08',
    business: 'James Arthur Construction Co.',
    email: 'sarthur@suddenlinkmail.com',
    sourceUrl: 'https://newbernbuilders.com/member/james-arthur-construction-co/',
    observation: 'Search results are mostly third-party directory pages, with no controlled project gallery or consultation funnel.',
    recommendedPackage: 'Media Website',
    subject: 'A website thought for James Arthur Construction',
    body: [
      'Hi James Arthur Construction team,',
      '',
      'I found the company through the local builders association, but search results are mostly third-party directory pages. I did not find an owned project gallery or direct consultation path that you control.',
      '',
      'I run New Bern Websites locally. We build complete builder sites with project photography, clear trust signals, and a simple inquiry flow.',
      '',
      "If that is worth improving, I can send a short outline of what I'd prioritize.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'gary-white-masonry-2026-08',
    business: "Gary White's Masonry, Inc.",
    email: 'glwhite81@gmail.com',
    sourceUrl: 'https://newbernbuilders.com/member/gary-whites-masonry-inc/',
    observation: 'The public profile has contact details but no project photos, specialties, or online estimate path.',
    recommendedPackage: 'Media Website',
    subject: "A website idea for Gary White's Masonry",
    body: [
      'Hi Gary,',
      '',
      'I found your company through the builders association. The profile gives customers a phone number, but it does not show the masonry specialties, finished work, or an online estimate path that could help them choose you.',
      '',
      'I run New Bern Websites locally. We build visual contractor sites that turn project proof into qualified estimate requests.',
      '',
      "If useful, I can send a short outline of the site I'd recommend.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'eagle-mark-contracting-2026-08',
    business: 'Eagle Mark Contracting LLC',
    email: 'eaglemarkcontracting@gmail.com',
    sourceUrl: 'https://newbernbuilders.com/member/eagle-mark-contracting-llc/',
    observation: 'The main exact-name result is a sparse association profile without services, projects, testimonials, or a quote path.',
    recommendedPackage: 'Media Website',
    subject: 'A website idea for Eagle Mark Contracting',
    body: [
      'Hi Arthur,',
      '',
      'I found Eagle Mark through the local builders association. The main exact-name result is a short directory profile, so prospects do not get to see your services, completed projects, testimonials, or a direct quote path.',
      '',
      'I run New Bern Websites locally. We build complete contractor sites around project proof, mobile clarity, and qualified inquiries.',
      '',
      "If useful, I can send a short outline of what I'd prioritize.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'magnolia-contracting-2026-08',
    business: 'Magnolia Contracting LLC',
    email: 'benitadees@gmail.com',
    sourceUrl: 'https://newbernbuilders.com/member/magnolia-contracting-llc/',
    observation: 'No matching owned site surfaced, and similarly named search results point to companies in other markets.',
    recommendedPackage: 'Media Website',
    subject: 'A local-search idea for Magnolia Contracting',
    body: [
      'Hi Magnolia Contracting team,',
      '',
      'I found your Havelock company through the builders association, but I did not find a matching owned website. Several similarly named results point to businesses in other markets, which can make it hard for a local prospect to know which company is yours.',
      '',
      'I run New Bern Websites locally. We build contractor sites that establish the right local identity, show project work, and create a direct quote path.',
      '',
      "If useful, I can send a short outline of how I'd approach it.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'last-stop-maintenance-2026-08',
    business: 'Last Stop Maintenance LLC',
    email: 'laststopllc252@gmail.com',
    sourceUrl: 'https://newbernbuilders.com/member/last-stop-maintenance-llc/',
    observation: 'The public profile lists phone numbers but no service description, service area, photos, or online request path.',
    recommendedPackage: 'Turnkey Website',
    subject: 'A website idea for Last Stop Maintenance',
    body: [
      'Hi Andy,',
      '',
      'I found Last Stop Maintenance through the builders association. The current profile lists phone numbers but does not explain your services, service area, past work, or give customers an online request path.',
      '',
      'I run New Bern Websites locally. We build complete service-business sites around clear services, mobile calls, and estimate requests.',
      '',
      "If useful, I can send a short outline of the pages I'd recommend.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'williams-sod-farm-2026-08',
    business: 'Williams Sod Farm',
    email: 'lindaswilliams@embarqmail.com',
    sourceUrl: 'https://newbernbuilders.com/member/williams-sod-farm/',
    observation: 'The homepage watering guide contains an obvious typo in a trust-sensitive educational section.',
    recommendedPackage: 'Media Website',
    subject: 'Small issue on the Williams Sod Farm site',
    body: [
      'Hi Williams Sod Farm team,',
      '',
      'I was reading the watering guidance on your homepage and noticed the sentence about keeping the soil beneath the sod wet contains an obvious typo. It is a small fix, but it appears in a trust-sensitive section customers may rely on after buying.',
      '',
      'I run New Bern Websites locally. We help visual home-service businesses pair useful guidance with a clearer quote path and stronger project imagery.',
      '',
      "If useful, I can send a short outline of the other changes I'd prioritize.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'mcclay-custom-homes-2026-08',
    business: 'McClay Custom Homes',
    email: 'bill@mcclaycustomhomes.com',
    sourceUrl: 'https://newbernbuilders.com/member/mcclay-custom-homes/',
    observation: 'The homepage repeats the same now-building heading twice with inconsistent Harbor spelling.',
    recommendedPackage: 'Media Website',
    subject: 'Small homepage issue for McClay Custom Homes',
    body: [
      'Hi Bill,',
      '',
      'I was looking through the McClay site and noticed the homepage repeats the same “Now Building” heading twice in a row, once with “Harbour” and once with “Harbor.” That kind of duplication can distract from otherwise strong home imagery.',
      '',
      'I run New Bern Websites locally. We build polished builder sites around project photography, community pages, and a clean consultation path.',
      '',
      "If useful, I can send a short outline of what I'd refine.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'natural-stone-yard-2026-08',
    business: 'The Natural Stone Yard',
    email: 'jeff.white@thenaturalstoneyard.com',
    sourceUrl: 'https://www.thenaturalstoneyard.com/',
    observation: 'The homepage labels its supplier section “OUR VENDERS,” and the footer still reads 2019.',
    recommendedPackage: 'Media Website',
    subject: 'Two small homepage issues',
    body: [
      'Hi Jeff,',
      '',
      'I was looking through The Natural Stone Yard site and noticed the supplier section is labeled “OUR VENDERS,” while the footer still reads 2019. Both are small details, but they can make an active visual business appear less current online.',
      '',
      'I run New Bern Websites locally. We build visual product and service sites around current project proof, clear inventory stories, and easier inquiries.',
      '',
      "If useful, I can send a short outline of what I'd change.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'enc-custom-builders-2026-08',
    business: 'ENC Custom Builders',
    email: 'contact@enccustomhomes.com',
    sourceUrl: 'https://newbernbuilders.com/member/enc-custom-builders-llc/',
    observation: 'The company site and current builders-association profile display different phone numbers.',
    recommendedPackage: 'Media Website',
    subject: 'Contact-data mismatch for ENC Custom Builders',
    body: [
      'Hi Matt,',
      '',
      'I noticed the ENC site displays one phone number while the current builders-association profile displays another. Even when both numbers work, inconsistent contact data can create doubt and cost calls from prospects comparing builders.',
      '',
      'I run New Bern Websites locally. We build and clean up builder sites around consistent local information, project proof, and a direct consultation path.',
      '',
      "If useful, I can send a short outline of what I'd prioritize.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'jak-cabinets-trim-2026-08',
    business: 'JAK Cabinets and Trim',
    email: 'amy@jakcabinetsandtrim.com',
    sourceUrl: 'https://newbernbuilders.com/member/jak-cabinets-and-trim/',
    observation: 'The New Bern showroom is buried below the Winterville address instead of having a prominent local journey.',
    recommendedPackage: 'Media Website',
    subject: 'A New Bern website idea for JAK Cabinets',
    body: [
      'Hi Amy,',
      '',
      'I noticed the homepage header leads with the Winterville address, while the New Bern showroom appears much lower in the site. A stronger New Bern-specific path could help nearby homeowners find the right showroom, work examples, and appointment step faster.',
      '',
      'I run New Bern Websites locally. We build visual home-improvement sites around showroom traffic, project proof, and qualified appointments.',
      '',
      "If useful, I can send a short outline of what I'd change.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'spectrum-building-remodeling-2026-08',
    business: 'Spectrum Building & Remodeling',
    email: 'jammon3@gmail.com',
    sourceUrl: 'https://newbernbuilders.com/member/spectrum-building-remodeling/',
    observation: 'The homepage repeats its custom-home and remodeling sections nearly word-for-word in consecutive blocks.',
    recommendedPackage: 'Media Website',
    subject: 'A homepage thought for Spectrum Building',
    body: [
      'Hi Jay,',
      '',
      'I was looking through the Spectrum site and noticed the custom-home and remodeling sections are repeated almost word-for-word in consecutive homepage blocks. Tightening that area could give more space to project proof and a clearer consultation path.',
      '',
      'I run New Bern Websites locally. We build contractor sites around strong portfolios, concise positioning, and qualified inquiries.',
      '',
      "If useful, I can send a short outline of what I'd change.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'pope-custom-homes-2026-08',
    business: 'Pope Custom Homes',
    email: 'bill@popecustomhomesinc.com',
    sourceUrl: 'https://newbernbuilders.com/member/pope-custom-homes-inc/',
    observation: 'The hero asks visitors to call for an appointment without displaying a phone number beside the call to action.',
    recommendedPackage: 'Media Website',
    subject: 'One conversion issue on the Pope Custom Homes site',
    body: [
      'Hi Bill,',
      '',
      'I noticed the Pope Custom Homes hero asks visitors to call for an appointment, but no phone number appears beside that call to action. The page then routes visitors through several generic “Browse” links, which adds friction at the moment they are ready to act.',
      '',
      'I run New Bern Websites locally. We build builder sites around project proof and a much clearer path to a consultation.',
      '',
      "If useful, I can send a short outline of what I'd prioritize.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
  {
    key: 'phillipward-2026-08',
    business: 'PhillipWard LLC',
    email: 'phillipbuild@gmail.com',
    sourceUrl: 'https://newbernbuilders.com/member/phillipward-llc/',
    observation: 'Exact-name search surfaces isolated listing references rather than an owned builder portfolio or consultation path.',
    recommendedPackage: 'Media Website',
    subject: 'A website idea for PhillipWard',
    body: [
      'Hi Phillip,',
      '',
      'I found PhillipWard through the builders association, but exact-name search mostly surfaces isolated property-listing references. I did not find an owned builder portfolio, service story, or direct consultation path that you control.',
      '',
      'I run New Bern Websites locally. We build complete builder sites around authentic project photography, local trust, and qualified inquiries.',
      '',
      "If useful, I can send a short outline of what I'd build first.",
      '',
      'Kyle',
      'New Bern Websites',
    ].join('\r\n'),
  },
];
